Fix fatal error: mysql/mysql.h (#1066)
judged.cc:41:18: fatal error: mysql/mysql.h: No such file or directory
   41 |         #include <mysql/mysql.h>
      |                  ^~~~~~~~~~~~~~~
compilation terminated.
Fix this error.
Debian 12 default openjdk version changes to 17.